package common

import (
	"time"

	"github.com/go-redis/redis/v9"
)

var RedisClient redis.Client

const (
	TEMPORAL_SUCESS_CODE = "SUCCESS"
	TEMPORAL_FAIL_CODE   = "FAILED"

	TEMPORAL_WF_TASK_TIMEOUT = time.Second * 30
	TEMPORAL_WF_EXEC_TIMEOUT = time.Second * 30
	TEMPORAL_WF_RUN_TIMEOUT  = time.Second * 30

	TEMPORAL_WF_RETRY_INTERVAL = time.Second
	TEMPORAL_WF_BACKOFF        = 1
	TEMPORAL_WF_MAX_INTERVAL   = time.Second * 10
	TEMPORAL_WF_MAX_ATTEMPT    = 1

	TEMPORAL_ACTIVITY_RETRY_INTERVAL = time.Second
	TEMPORAL_ACTIVITY_BACKOFF        = 1
	TEMPORAL_ACTIVITY_MAX_INTERVAL   = time.Second * 10
	TEMPORAL_ACTIVITY_MAX_ATTEMPT    = 1
	TEMPORAL_ACTIVITE_TIMEOUT        = 30 * time.Second

	VM_TASK_QUEUE         = "COMPUTE_TASK_QUEUE"
	VM_INFO_WORKFLOW_ID   = "VM_INFO_WORKFLOW"
	VM_CREATE_WORKFLOW_ID = "VM_CREATE_WORKFLOW"
	VM_UPDATE_WORKFLOW_ID = "VM_UPDATE_WORKFLOW"
	VM_DELETE_WORKFLOW_ID = "VM_DELETE_WORKFLOW"
)
