# MIT License
# Copyright(c) 2022 Futurewei Cloud
#     Permission is hereby granted,
#     free of charge, to any person obtaining a copy of this software and associated documentation files(the "Software"), to deal in the Software without restriction,
#     including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and / or sell copies of the Software, and to permit persons
#     to whom the Software is furnished to do so, subject to the following conditions:
#     The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#     THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#     FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
#     WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

apiVersion: v1
kind: Service
metadata:
  name: merak-ntest-service
  namespace: merak
spec:
  selector:
    app: merak-ntest
  ports:
    - protocol: TCP
      name: grpc
      port: 40051
      targetPort: ntest-grpc
  type: ClusterIP
---
# Merak ntest Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: merak-ntest
  namespace: merak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: merak-ntest
  template:
    metadata:
      labels:
        app: merak-ntest
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: merak-ntest
        image: meraksim/merak-ntest:dev
        imagePullPolicy: Always
        ports:
          - containerPort: 40051
            name: ntest-grpc
        env:
        - name: "TEMPORAL"
          value: "temporaltest-frontend.default.svc.cluster.local"
---
# Merak Ntest Worker Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: merak-ntest-worker
  namespace: merak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: merak-ntest-worker
  template:
    metadata:
      labels:
        app: merak-ntest-worker
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: merak-ntest-worker
        image: meraksim/merak-ntest-worker:dev
        imagePullPolicy: Always
        env:
        - name: "TEMPORAL"
          value: "temporaltest-frontend.default.svc.cluster.local"
