apiVersion: apps/v1
kind: Deployment
metadata:
  name: ryu-deployment
spec:
  selector:
    matchLabels:
      app: ryu
  replicas: 5
  template:
    metadata:
      labels:
        app: ryu
    spec:
     #hostNetwork: true
      containers:
      - name: ryu
        image: osrg/ryu
        args:
          - ryu-manager
          - ./ryu/ryu/app/simple_switch_13.py
        ports:
        - containerPort: 6653
          name: openflow
